name: konterapps
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  charts_flutter: ^0.9.0
  timeline_tile: ^0.1.2
  bubble_tab_indicator: ^0.1.4
  carousel_slider: ^2.2.1
  lottie: ^0.4.1
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # - assets/images/payment.png
    # - assets/images/phone.png
    # - assets/images/voucher.png
    # - assets/lottiefiles/delivery-loader.json
    # - assets/lottiefiles/bluecommerce.json
    # - assets/lottiefiles/shopcard.json
    # - assets/lottiefiles/emptybox.json
    # - assets/fonts/FormulaCondensed.otf
    # - assets/fonts/FreeSerif.otf
    # - assets/fonts/MadeCanvas.otf
    # - assets/fonts/OregonLDO.ttf
    # - assets/fonts/PlayfairDisplay.ttf
    - assets/lottiefiles/
    - assets/images/
    # - assets/fonts/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: FormulaCond
      fonts:
        - asset: assets/fonts/FormulaCondensed.otf
        
    - family: FreeSerif
      fonts:
        - asset: assets/fonts/FreeSerif.otf

    - family: MadeCanvas
      fonts:
        - asset: assets/fonts/MadeCanvas.otf

    - family: OregonLDO
      fonts:
        - asset: assets/fonts/OregonLDO.ttf
        
    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #